### ISSUE TITLE
Remote connection

### ISSUE THREAD

**Issue by odlan** [omelhus/EyefiServerSynology#1]
Hello first thank's for your work. It is working very well in its standard configuration.
With your python script I am able to move my photos from my Eye-Fi card to my local Synology server when I am in same LAN.
Now I want to know if it is possible transfer my photos to my remote address when I am not in LAN.
I have a domain http://pippo.com and I have the Synology server behind it. I can start the demon on 192.168.1.x but how can tell to transfer the photos to http://pippo.com ?? I have open on my router  port 59278 on 192.168.1.x
Thank you
andrea

**Comment by omelhus** [comment]
Hey Andrea,

Thanks! I'm sorry, but I really don't think that what you cant to achieve is possible. I think it's better for you to use Eye-Fi with the built-in FTP upload feature.
- Ole
